# Generated by Django 5.1.3 on 2024-11-25 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_fotografia_categora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='categora',
            new_name='categoria',
        ),
    ]
